spring:
  datasource:
    url: "jdbc:sqlserver://database-1.c4rtmve0utkd.us-east-1.rds.amazonaws.com:1433"
    username: "admin"
    password: "Welcome2BSG"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  h2:
    console:
      enabled: true
